# Generated by Django 5.1.4 on 2024-12-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthday', models.DateField(null=True)),
                ('class_assigned', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
    ]
