# Generated by Django 5.1.4 on 2024-12-24 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('counselor_id', models.AutoField(primary_key=True, serialize=False)),
                ('counselor_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('class_assigned', models.CharField(blank=True, max_length=50)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselors', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('report_role', models.CharField(max_length=50)),
                ('report_status', models.CharField(max_length=50)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='administration.counselor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='teachers.teacher')),
            ],
        ),
    ]
