# Generated by Django 5.1.4 on 2024-12-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_text',
            field=models.TextField(blank=True),
        ),
    ]
